apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  annotations:
    # NLB 타입을 유지하여 빠른 성능과 고정 IP 기반 운영 가능하게 설정
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: eks-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80 # 외부에서 접속할 포트
      targetPort: 80 # Nginx 컨테이너 내부 포트
  type: LoadBalancer
